syms x y z vx vy vz phi theta psi omegax omegay omegaz 
syms m L  k b g Kd Ixx Iyy Izz cm UU
xx = [x, y, z, vx, vy, vz, phi, theta, psi, omegax, omegay, omegaz]
xdot = [vx, vy,vz, -Kd*vx/m+k*cm/m*(sin(psi)*sin(phi)+cos(psi)*cos(phi)*sin(theta))*UU,...
    -Kd*vy/m+k*cm/m*(cos(phi)*sin(psi)*sin(theta) - cos(psi)*sin(phi))*UU, ...
    -Kd*vz/m-g+k*cm/m*(cos(theta)*cos(phi))*UU, ...
    omegax + omegay*(sin(phi)*tan(theta))+omegaz*(cos(phi)*tan(theta)),...
    omegay*cos(phi)-omegaz*sin(phi),...
    omegay*sin(phi)/cos(theta)+omegaz*cos(phi)/cos(theta),...
    -(Iyy-Izz)*omegay*omegaz/Ixx, -(Izz-Ixx)*omegax*omegaz/Iyy,...
    -(Ixx-Iyy)*omegax*omegay/Izz]
jacobian(xdot,xx)
    